### ISSUE TITLE
Bad Request Error

### ISSUE THREAD

**Issue by renatofertec** [cenit-io/cenit#3017] opened 2023-03-13 19:04 UTC
I'm having problems logging in to Cenit IO locally through Docker-compose, even following the steps that the documentation suggests I always end up getting the same bad request error.

![22b1a507-fe2e-4364-9a10-b8f7c69f74cd](https://user-images.githubusercontent.com/113617116/224802826-6f77807f-2ae2-4d46-b886-6546f5d600f4.jpg)

Dell Inc. XPS 13 9300
 - OS: Fedora36
 - Browsers: Brave (1.48.171) and FireFox (110.0.1)

**Comment by frappierer** [comment] 2023-03-18 16:41
Same here

**Comment by yoandrypa** [comment] 2023-05-08 13:31
This error was caused by the requirement of 2 environment variables related to client_id and client_secret, needed by the oauth2 process.

This problem is already fixed in the user interface.
These variables are no longer required.

**Closed by yoandrypa** 2023-05-08 13:31 UTC
